version: 2
updates:
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    reviewers:
      - "luisdiher22"
    assignees:
      - "luisdiher22"
    commit-message:
      prefix: "chore"
      include: "scope"
  
  # Node.js dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    reviewers:
      - "luisdiher22"
    assignees:
      - "luisdiher22"
    commit-message:
      prefix: "chore"
      include: "scope"
  
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    reviewers:
      - "luisdiher22"
    assignees:
      - "luisdiher22"
    commit-message:
      prefix: "ci"
      include: "scope"
